name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        sudo apt-get remove mysql-server --purge
        ./install-operator-sdk.sh
        git clone --depth 1 -b "v0.6.0" --single-branch https://github.com/k8s-school/kind-travis-ci.git
        ./kind-travis-ci/kind/k8s-create.sh -s
        operator-sdk generate k8s
        operator-sdk generate crds
        GO111MODULE="on" operator-sdk build "${OP_IMAGE}"
        sed "s|REPLACE_IMAGE|${OP_IMAGE}|g" "./deploy/operator.yaml.tpl" \
          > "./deploy/operator.yaml"
        kind load docker-image "${OP_IMAGE}"
        ./install-operator-sdk.sh
        git clone --depth 1 -b "v0.6.0" --single-branch https://github.com/k8s-school/kind-travis-ci.git
        ./kind-travis-ci/kind/k8s-create.sh -s
        kubectl create namespace qserv
        kubectl config set-context $(shell kubectl config current-context) --namespace=qserv
        ./deploy.sh -n qserv
        ./wait-operator-ready.sh
        kubectl apply -k base -n qserv
        ./wait-qserv-ready.sh
        ./run-integration-tests.sh
